---
title: "Assignment Validation"
date: 'r Sys.Date()'
author: "WSP | Parsons Brinckerhoff"
output: html_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(cache=FALSE,echo=FALSE,
                      message=FALSE,warning=FALSE,error=TRUE)
options(scipen=999) # removes sci notation
```


```{r setup}
library(outviz)
library(dplyr)
library(knitr)
library(ggplot2)
library(tcadr)
```


```{r, include = FALSE}
# These variables identify the pertinent field names and any other variables. In
# gisdk_tools, these field names are fixed. A future enhancement would be to
# pass in these field names to the RMD using 
# args <- commandArgs(trailingOnly = TRUE)
volume_var <- "Flow_Daily"
count_id_var <- "CountID"
count_var <- "DailyCount"
fac_types <- c("Freeway", "MLHighway", "TLHighway", "PrArterial",
        "MinArterial", "Collector", "Local", "Total")
area_types <- c("Urban", "Suburban", "Rural")

# Read in the links table.  readr or tcadr could be used here.
links <- readr::read_csv("links.csv")
  
# create count/volume fields with standard name
links$volume <- links[[volume_var]]
links$count <- links[[count_var]]
links$count_id <- links[[count_id_var]]

# Remove centroid connectors, ramps, and links with no counts
links <- links %>%
  filter(!(is.na(count)), HCMType != "CC", is.na(ramp))

links <- links %>%
  mutate(
    HCMType = factor(HCMType, levels = fac_types, ordered = TRUE),
    area_name = factor(AreaType, levels = area_types, ordered = TRUE)
  ) %>%
    rename(
    facility_group = HCMType,
    screenline = Screenline
  ) %>%
  group_by(facility_group, screenline, count_id) %>%
  summarize(
    # Some 1-way pair links can have different area types
    area_name = first(area_name),
    count = sum(count),
    volume = sum(volume)
  ) %>%
  ungroup()
  
# make a copy of the count field for outviz grouping
links$Volume_Group <- links$count
links$Volume_Group <- outviz:::cut_volumes(links$Volume_Group)
```

```{r targets}
rmse_facility_group <- data_frame(
  facility_group = c("Freeway", "MLHighway", "TLHighway", "PrArterial",
        "MinArterial", "Collector", "Local", "Total"),
  Target = c(25, 35, 50, 50, 65, 100, 100, 40)
)

flow_volume_group <- data_frame(
  `Volume_Group` = c(
    "0 - 5000",
    "5000 - 10000",
    "10000 - 15000",
    "15000 - 20000",
    "20000 - 30000",
    "> 30000",
    "Total",
    "20000 - 40000",
    "40000 - 60000",
    "> 60000"
  ),
  Target = c(
    100,
    45,
    35,
    30,
    27,
    25,
    10,
    25,
    20,
    19
  )
)

rmse_volume_group <- data_frame(
  `Volume_Group` = c(
    "0 - 5000",
    "5000 - 10000",
    "10000 - 15000",
    "15000 - 20000",
    "20000 - 30000",
    "30000 - 50000",
    "50000 - 60000",
    "> 60000",
    "Total",
    "20000 - 40000",
    "40000 - 60000"
  ),
  Target = c(
    100,
    45,
    35,
    30,
    27,
    25,
    20,
    19,
    40,
    25,
    20
  )
)
```

```{r validation}
plotly_validation(links, "volume", "count", "facility_group", id = "count_id")
plot_validation(links, "volume", "count", show_lm = TRUE) +
  facet_wrap(~ area_name, scales = "free")
```

```{r, fig.width=12, fig.height=12}
plot_validation(links, "volume", "count") +
  facet_wrap(~ facility_group, scales = "free")
```


```{r mdd}
plotly_mdd(links, "volume", "count", color_field = "facility_group", id = "count_id")
```

```{r rmse}
link_stats_table(
  links, "volume", "count", group_field = "facility_group", type = "rmse") %>%
  left_join(rmse_facility_group, by = "facility_group") %>%
  mutate_at(
    vars(`Number of Links`), .funs = funs(format(round(., 0), big.mark = ","))
  ) %>%
  kable(digits = 2, caption = "RMSE by Facility Group", align = "lrrr")

link_stats_table(
  links, "volume", "count", group_field = "area_name",type = "rmse") %>%
  mutate_at(
    vars(`Number of Links`), .funs = funs(format(round(., 0), big.mark = ","))
  ) %>%
  kable(digits = 2, caption = "RMSE by Area Type", align = "lrr")

link_stats_table(
  links, "volume", "count", group_field = "Volume_Group", type = "rmse") %>%
  left_join(rmse_volume_group, by = "Volume_Group") %>%
  mutate_at(
    vars(`Number of Links`), .funs = funs(format(round(., 0), big.mark = ","))
  ) %>%
  kable(digits = 2, caption = "RMSE by Volume Group", align = "lrrr")
```

```{r flow}
link_stats_table(
  links, "volume", "count", group_field = "facility_group", type = "flow") %>%
  mutate_at(
    vars(`Observed Flow`, `Model Flow`),
    .funs = funs(format(round(., 0), big.mark = ","))
  ) %>%
  kable(digits = 2, caption = "Total Flow by Facility Group", align = "lrrr")

link_stats_table(
  links, "volume", "count", group_field = "Volume_Group", type = "flow") %>%
  left_join(flow_volume_group, by = "Volume_Group") %>%
  mutate_at(
    vars(`Observed Flow`, `Model Flow`),
    .funs = funs(format(round(., 0), big.mark = ","))
  ) %>%
  kable(digits = 2, caption = "Total Flow by Volume Group", align = "lrrrr")

link_stats_table(
  links, "volume", "count", group_field = "area_name", type = "flow") %>%
  mutate_at(
    vars(`Observed Flow`, `Model Flow`),
    .funs = funs(format(round(., 0), big.mark = ","))
  ) %>%  
  kable(digits = 2, caption = "Total Flow by Area Type", align = "lrrr")

link_stats_table(
  links %>% filter(screenline != 0),
  "volume", "count", group_field = "screenline", type = "flow") %>%
  mutate_at(
    vars(`Observed Flow`, `Model Flow`),
    .funs = funs(format(round(., 0), big.mark = ","))
  ) %>%
  mutate(Target = 10) %>%
  kable(digits = 2, caption = "Total Flow by Screenline", align = "lrrrr")
```

```{r link_targets}
volString <- paste0("volume", " > 10000")
link_targets(links, "volume", "count",
             "facility_group == 'Freeway'", volString) %>%
  kable(digits = 2, caption = "Individual Link Targets")
```
